sudo: false

notifications:
    email: false

branches:
    only:
        - master

os:
    - linux

language: python
python:
    - 3.7

install:
    - pip install tox-travis>=0.11

script:
    - tox
