name: facet
channels:
  - defaults
dependencies:
  - pip>=20.1.1
  - python=3.6
  - pip:
    - click>=7.0
    - tox>=3.5
    - unidecode>=1.1.1
    - PyYAML>=5.3.1
    - dicttoxml>=1.7.4
    - pandas>=0.24.2
    - nltk>=3.4.1
    - spacy>=2.1.3
    - redis>=3.2.1
    - hiredis>=1.0.0
    - elasticsearch>=7.0.0,<8.0.0
    - pymongo>=3.10
    - Sphinx[reST]>=3.0
    - sphinx_rtd_theme[reST]>=0.4.3
    - sphinx-click[reST]>=2.3
    - flake8[lint]>=3.5
    - coverage[coverage]>=4.5
    - pytest[test]>=5.3
