name: quickerumls
channels:
  - defaults
dependencies:
  - ca-certificates=2019.1.23
  - certifi=2019.3.9
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libstdcxx-ng=8.2.0
  - ncurses=6.1
  - openssl=1.1.1b
  - pip=19.0.3
  - python=3.7.3
  - readline=7.0
  - setuptools=41.0.0
  - sqlite=3.27.2
  - tk=8.6.8
  - wheel=0.33.1
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - alabaster==0.7.12
    - atomicwrites==1.3.0
    - attrs==19.1.0
    - babel==2.7.0
    - benchmarker==4.0.1
    - blis==0.2.4
    - chardet==3.0.4
    - click==7.0
    - codecov==2.0.15
    - colorama==0.4.1
    - coverage==4.5.4
    - cymem==2.0.2
    - dicttoxml==1.7.4
    - docutils==0.15.2
    - en-core-web-sm==2.1.0
    - entrypoints==0.3
    - filelock==3.0.12
    - flake8==3.7.7
    - flatbuffers==1.11
    - funcsigs==1.0.2
    - hiredis==1.0.0
    - idna==2.8
    - imagesize==1.1.0
    - importlib-metadata==0.19
    - jinja2==2.10.1
    - jsonschema==2.6.0
    - leveldb==0.194
    - markupsafe==1.1.1
    - mccabe==0.6.1
    - modin==0.5.4
    - more-itertools==7.2.0
    - msgpack==0.6.1
    - murmurhash==1.0.2
    - nltk==3.4.1
    - numpy==1.16.2
    - packaging==19.0
    - pandas==0.24.2
    - plac==0.9.6
    - pluggy==0.12.0
    - plyvel==1.0.5
    - preshed==2.0.1
    - py==1.8.0
    - pycodestyle==2.5.0
    - pyflakes==2.1.1
    - pygments==2.4.2
    - pymongo==3.9.0
    - pyparsing==2.4.1.1
    - pytest==5.0.1
    - python-dateutil==2.8.0
    - pytz==2019.1
    - pyyaml==5.1.1
    - quickerumls==0.8
    - ray==0.7.1
    - redis==3.2.1
    - requests==2.21.0
    - ruamel.yaml==0.16.1
    - ruamel.yaml.clib==0.1.2
    - six==1.12.0
    - snowballstemmer==1.9.0
    - spacy==2.1.3
    - sphinx==2.1.2
    - sphinx-rtd-theme==0.4.3
    - sphinxcontrib-applehelp==1.0.1
    - sphinxcontrib-devhelp==1.0.1
    - sphinxcontrib-htmlhelp==1.0.2
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.2
    - sphinxcontrib-serializinghtml==1.1.3
    - srsly==0.0.5
    - thinc==7.0.4
    - tqdm==4.31.1
    - typing==3.7.4
    - unidecode==1.0.23
    - urllib3==1.24.1
    - wasabi==0.2.1
    - wcwidth==0.1.7
    - zipp==0.5.2
