name: facet
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.2
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1g
  - pip=20.1.1
  - python=3.6.10
  - readline=8.0
  - setuptools=47.3.0
  - sqlite=3.32.2
  - tk=8.6.10
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - alabaster==0.7.12
    - appdirs==1.4.4
    - attrs==19.3.0
    - babel==2.8.0
    - blis==0.4.1
    - catalogue==1.0.0
    - chardet==3.0.4
    - click==7.1.2
    - coverage==5.1
    - cymem==2.0.3
    - dicttoxml==1.7.4
    - distlib==0.3.0
    - docutils==0.16
    - elasticsearch==7.8.0
    - en-core-web-sm==2.3.0
    - filelock==3.0.12
    - flake8==3.8.3
    - hiredis==1.0.1
    - idna==2.9
    - imagesize==1.2.0
    - importlib-metadata==1.6.1
    - importlib-resources==2.0.1
    - jinja2==2.11.2
    - joblib==0.15.1
    - markupsafe==1.1.1
    - mccabe==0.6.1
    - more-itertools==8.4.0
    - murmurhash==1.0.2
    - nltk==3.5
    - numpy==1.19.0
    - packaging==20.4
    - pandas==1.0.5
    - pbr==5.4.5
    - plac==1.1.3
    - pluggy==0.13.1
    - preshed==3.0.2
    - psycopg2==2.8.5
    - py==1.8.2
    - pycodestyle==2.6.0
    - pyflakes==2.2.0
    - pygments==2.6.1
    - pyparsing==2.4.7
    - pytest==5.4.3
    - python-dateutil==2.8.1
    - pytz==2020.1
    - pyyaml==5.3.1
    - redis==3.5.3
    - regex==2020.6.8
    - requests==2.24.0
    - six==1.15.0
    - snowballstemmer==2.0.0
    - spacy==2.3.0
    - sphinx==3.1.1
    - sphinx-click==2.3.2
    - sphinx-rtd-theme==0.5.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - srsly==1.0.2
    - thinc==7.4.1
    - toml==0.10.1
    - tox==3.15.2
    - tqdm==4.46.1
    - unidecode==1.1.1
    - urllib3==1.25.9
    - virtualenv==20.0.23
    - wasabi==0.6.0
    - wcwidth==0.2.4
    - zipp==3.1.0

