DEFAULT:
    query: null
    alpha: 0.7
    similarity: jaccard
    formatter: csv
    output: null
    tokenizer: ws
    database: dict
    host: localhost
    port: 4444

match:
    install: data/umls_midsmall/MRCONSO.RRF
    extra: delimiter=|, keys=[14]

umls:
    install: data/umls_midsmall
    conso_db: dict
    cuisty_db: dict
