FacetDict:
    class: facet
    matcher:
        class: simstring
        db:
            class: dict
            filename: db/test
            # NOTE: Access mode did not affect installation?
            access_mode: r
        cache_db: null
        alpha: 0.7
        similarity: cosine
        ngram: character
        # ngram:
        #     class: character
        #     n: 3
        #     boundary: " "
        # serializer: json
        # serializer:
        #     class: json
        #     encoding: utf-8
        #     form: NFKD
    tokenizer: ws
    # tokenizer:
    #     class: nltk
    #     language: english
    # tokenizer:
    #     class: spacy
    #     language: en
    formatter: json
    install:
        data: data/umls_midsmall/MRCONSO.RRF
        overwrite: false
        delimiter: "|"
        cols: 14


FacetRedis:
    class: facet
    matcher:
        class: simstring
        db:
            class: redis
            host: localhost
            port: 6379
            id: 3
        cache_db: null
        alpha: 0.7
        similarity: cosine
        ngram: character
    tokenizer: ws
    formatter: json
    install:
        data: data/umls_midsmall/MRCONSO.RRF
        overwrite: false
        delimiter: "|"
        cols: 14


FacetSQL:
    class: facet
    matcher:
        class: simstring
        db:
            class: sqlite
            filename: ":memory:"
            table: simstring
            access_mode: c
            serializer: json
            check_same_thread: false
        cache_db: null
        alpha: 0.7
        similarity: cosine
        ngram: character
    tokenizer: ws
    formatter: json
    install:
        data: data/umls_midsmall/MRCONSO.RRF
        overwrite: false
        delimiter: "|"
        cols: 14

UMLSDict:
    class: umlsfacet
    conso_db:
        class: dict
        filename: null
    cuisty_db:
        class: dict
        filename: null
    matcher:
        class: simstring
        db:
            class: dict
            filename: null
        cache_db: null
        alpha: 0.7
        similarity: cosine
        ngram: character
    tokenizer: ws
    formatter: json
    install: data/umls_midsmall


UMLSRedis:
    class: umlsfacet
    conso_db:
        class: redis
        host: localhost
        port: 6379
        id: 0
        serializer: json
    cuisty_db:
        class: redis
        host: localhost
        port: 6379
        id: 1
        serializer: json
    matcher:
        class: simstring
        db:
            class: redis
            host: localhost
            port: 6379
            id: 2
        cache_db: null
        alpha: 0.7
        similarity: cosine
        ngram: character
    tokenizer: ws
    formatter: json
    install: data/umls_midsmall


UMLSSQL:
    class: umlsfacet
    conso_db:
        class: sqlite
        filename: ":memory:"
        table: conso
        access_mode: c
        serializer: json
        check_same_thread: false
    # conso_db:
    #     class: sqlite
    #     filename: :memory:
    #     table: cuisty
    #     access_mode: c
    #     serializer: json
    #     check_same_thread: false
    matcher:
        class: simstring
        db:
            class: sqlite
            filename: ":memory:"
            table: simstring
            access_mode: c
            serializer: json
            check_same_thread: false
        cache_db: null
        alpha: 0.7
        similarity: cosine
        ngram: character
    tokenizer: ws
    formatter: json
    install: data/umls_midsmall
