FacetMemory:
    class: facet
    use_proxy_install: false
    matcher:
        class: simstring
        db: dict
        alpha: 0.7
        similarity: cosine
        ngram: character
    tokenizer: ws
    formatter: json
    install:
        data: data/umls_midsmall/MRCONSO.RRF
        delimiter: "|"
        cols: 14


FacetFile:
    class: facet
    matcher:
        class: simstring
        db:
            class: dict
            filename: db/simstring
            use_pipeline: true
        alpha: 0.7
        similarity: cosine
        ngram: character
    tokenizer: ws
    formatter: json
    install:
        data: data/umls_midsmall/MRCONSO.RRF
        delimiter: "|"
        cols: 14


FacetRedis:
    class: facet
    matcher:
        class: simstring
        db:
            class: redis
            # db_type: nkv
            host: localhost
            port: 6379
            id: 3
            use_pipeline: true
        cache_db: null
        alpha: 0.7
        similarity: cosine
        ngram: character
        # ngram:
        #     class: word
        #     n: 2
    tokenizer: ws
    formatter: json
    install:
        data: data/umls_midsmall/MRCONSO.RRF
        delimiter: "|"
        cols: 14


FacetSQL:
    class: facet
    matcher:
        class: simstring
        db:
            class: sqlite
            filename: db/simstring
            table: facet
            access_mode: c
            serializer: json
            check_same_thread: false
        cache_db: null
        alpha: 0.7
        similarity: cosine
        ngram: character
    tokenizer: ws
    formatter: json
    install:
        data: data/umls_midsmall/MRCONSO.RRF
        delimiter: "|"
        cols: 14


UMLSMemory:
    class: umlsfacet
    use_proxy_install: false
    conso_db: dict
    cuisty_db: dict
    matcher:
        class: simstring
        db: dict
        alpha: 0.7
        similarity: cosine
        ngram: character
    tokenizer: ws
    formatter: json
    install:
        data: data/umls_midsmall
        # cui_valids: null
        # sty_valids: null


UMLSFile:
    class: umlsfacet
    conso_db:
        class: dict
        filename: db/conso
        use_pipeline: true
    cuisty_db:
        class: dict
        filename: db/cuisty
        use_pipeline: true
    matcher:
        class: simstring
        db:
            class: dict
            filename: db/simstring
            use_pipeline: true
        alpha: 0.7
        similarity: cosine
        ngram: character
    tokenizer: ws
    formatter: json
    install: data/umls_midsmall


UMLSRedis:
    class: umlsfacet
    conso_db:
        class: redis
        host: localhost
        port: 6379
        id: 0
        serializer: json
        use_pipeline: true
    cuisty_db:
        class: redis
        host: localhost
        port: 6379
        id: 1
        serializer: json
        use_pipeline: true
    matcher:
        class: simstring
        db:
            class: redis
            host: localhost
            port: 6379
            id: 2
            serializer: json
            use_pipeline: true
        cache_db: null
        alpha: 0.7
        similarity: cosine
        ngram: character
    tokenizer: ws
    formatter: json
    install: data/umls_midsmall


UMLSSQL:
    class: umlsfacet
    conso_db:
        class: sqlite
        filename: db/conso
        table: conso
        access_mode: c
        serializer: json
        check_same_thread: false
    cuisty_db:
        class: sqlite
        filename: db/cuisty
        table: cuisty
        access_mode: c
        serializer: json
        check_same_thread: false
    matcher:
        class: simstring
        db:
            class: sqlite
            filename: db/simstring
            table: simstring
            access_mode: c
            serializer: json
            check_same_thread: false
        cache_db: null
        alpha: 0.7
        similarity: cosine
        ngram: character
    tokenizer: ws
    formatter: json
    install: data/umls_midsmall
