SimpleMemory:
    install: data/install/american-english


AutoMemory:
    install: data/install/american-english
    query: data/sample.txt
    formatter: json
    output: annotations.json


SimpleRedis:
    matcher:
        class: simstring
        db: redis
    install: data/install/american-english


FacetMemory:
    class: facet
    matcher:
        class: simstring
        db: dict
        alpha: 0.7
        similarity: jaccard
        ngram: character
    tokenizer: alphanumeric
    formatter: json
    install:
        data: data/umls/MRCONSO.RRF
        delimiter: "|"
        cols: 14


FacetFile:
    class: facet
    matcher:
        class: simstring
        db:
            class: dict
            filename: db/simstring
            use_pipeline: true
        alpha: 0.7
        similarity: jaccard
        ngram: character
    tokenizer: alphanumeric
    formatter: json
    use_proxy_install: true
    install:
        data: data/umls/MRCONSO.RRF
        delimiter: "|"
        cols: 14


FacetRedis:
    class: facet
    matcher:
        class: simstring
        db:
            class: redis
            host: localhost
            port: 6379
            n: 3
            access_mode: c
            use_pipeline: true
        cache_db: null
        alpha: 0.7
        similarity: jaccard
        ngram: character
    tokenizer: alphanumeric
    formatter: json
    use_proxy_install: true
    install:
        data: data/umls/MRCONSO.RRF
        delimiter: "|"
        cols: 14


FacetSQL:
    class: facet
    matcher:
        class: simstring
        db:
            class: sqlite
            filename: db/simstring
            table: facet
            access_mode: c
            serializer: json
            check_same_thread: false
        cache_db: null
        alpha: 0.7
        similarity: jaccard
        ngram: character
    tokenizer: alphanumeric
    formatter: json
    use_proxy_install: true
    install:
        data: data/umls/MRCONSO.RRF
        delimiter: "|"
        cols: 14


FacetES:
    class: facet
    matcher:
        class: elasticsearch-simstring
        db:
            index: facet
            host: localhost:9200
            use_pipeline: true
            access_mode: c
        cache_db: null
        alpha: 0.7
        similarity: jaccard
        ngram: character
    tokenizer: alphanumeric
    formatter: json
    install:
        data: data/umls/MRCONSO.RRF
        delimiter: "|"
        cols: 14


FacetMongo:
    class: facet
    matcher:
        class: mongo-simstring
        db:
            database: facet
            host: localhost
            port: 27017
            use_pipeline: true
            access_mode: c
        cache_db: null
        alpha: 0.7
        similarity: jaccard
        ngram: character
    tokenizer: alphanumeric
    formatter: json
    install:
        data: data/umls/MRCONSO.RRF
        delimiter: "|"
        cols: 14


FacetESFuzzy:
    class: facet
    matcher:
        class: elasticsearch-fuzzy
        db:
            index: facet
            host: localhost:9200
            use_pipeline: true
            access_mode: c
        cache_db: null
    tokenizer: alphanumeric
    formatter: json
    install:
        data: data/umls/MRCONSO.RRF
        delimiter: "|"
        cols: 14


UMLSMemory:
    class: umlsfacet
    conso_db: dict
    cuisty_db: dict
    matcher:
        class: simstring
        db: dict
        alpha: 0.7
        similarity: jaccard
        ngram: character
    tokenizer: alphanumeric
    formatter: json
    install:
        data: data/umls


UMLSFile:
    class: umlsfacet
    conso_db:
        class: dict
        filename: db/conso
        use_pipeline: true
    cuisty_db:
        class: dict
        filename: db/cuisty
        use_pipeline: true
    matcher:
        class: simstring
        db:
            class: dict
            filename: db/simstring
            use_pipeline: true
        alpha: 0.7
        similarity: jaccard
        ngram: character
    tokenizer: alphanumeric
    formatter: json
    use_proxy_install: true
    install: data/umls


UMLSRedis:
    class: umlsfacet
    conso_db:
        class: redis
        host: localhost
        port: 6379
        n: 0
        access_mode: c
        serializer: json
        use_pipeline: true
    cuisty_db:
        class: redis
        host: localhost
        port: 6379
        n: 1
        access_mode: c
        serializer: json
        use_pipeline: true
    matcher:
        class: simstring
        db:
            class: redis
            host: localhost
            port: 6379
            n: 2
            access_mode: c
            serializer: pickle
            use_pipeline: true
        cache_db: null
        alpha: 0.7
        similarity: jaccard
        ngram: character
    tokenizer: alphanumeric
    formatter: json
    use_proxy_install: true
    install: data/umls


UMLSSQL:
    class: umlsfacet
    conso_db:
        class: sqlite
        filename: db/umls
        table: conso
        access_mode: c
        serializer: json
        check_same_thread: false
    cuisty_db:
        class: sqlite
        filename: db/umls
        table: cuisty
        access_mode: c
        serializer: json
        check_same_thread: false
    matcher:
        class: simstring
        db:
            class: sqlite
            filename: db/umls
            table: simstring
            access_mode: c
            serializer: pickle
            check_same_thread: false
        cache_db: null
        alpha: 0.7
        similarity: jaccard
        ngram: character
    tokenizer: alphanumeric
    formatter: json
    use_proxy_install: true
    install: data/umls


UMLSESS:
    class: umlsfacet
    conso_db:
        class: sqlite
        filename: db/umls
        table: conso
        access_mode: c
        serializer: json
        check_same_thread: false
    cuisty_db:
        class: sqlite
        filename: db/umls
        table: cuisty
        access_mode: c
        serializer: json
        check_same_thread: false
    matcher:
        class: elasticsearch-simstring
        db:
            index: umls
            host: localhost
            port: 9200
            use_pipeline: true
            access_mode: c
        cache_db: null
        alpha: 0.7
        similarity: jaccard
        ngram: character
    tokenizer: alphanumeric
    formatter: json
    install: data/umls


UMLSESR:
    class: umlsfacet
    conso_db:
        class: redis
        host: localhost
        port: 6379
        n: 0
        access_mode: c
        use_pipeline: true
    cuisty_db:
        class: redis
        host: localhost
        port: 6379
        n: 1
        access_mode: c
        use_pipeline: true
    matcher:
        class: elasticsearch-simstring
        db:
            index: umls
            port: localhost:9200
            use_pipeline: true
            access_mode: c
        cache_db: null
        alpha: 0.7
        similarity: jaccard
        ngram: character
    tokenizer: alphanumeric
    formatter: json
    install: data/umls


UMLSMongo:
    class: umlsfacet
    conso_db:
        class: sqlite
        filename: db/umls
        table: conso
        access_mode: c
        serializer: json
        check_same_thread: false
    cuisty_db:
        class: sqlite
        filename: db/umls
        table: cuisty
        access_mode: c
        serializer: json
        check_same_thread: false
    matcher:
        class: mongo-simstring
        db:
            database: umls
            host: localhost
            port: 27017
            use_pipeline: true
            access_mode: c
        cache_db: null
        alpha: 0.7
        similarity: jaccard
        ngram: character
    tokenizer: alphanumeric
    formatter: json
    install: data/umls
