Install:
    class: umlsfacet
    conso_db:
        class: sqlite
        uri: db/umls
        table: conso
        access_mode: c
        use_pipeline: true
        connect: true
        serializer: pickle
    cuisty_db:
        class: sqlite
        uri: db/umls
        table: cuisty
        access_mode: c
        use_pipeline: true
        connect: true
        serializer: pickle
    matcher:
        class: elasticsearch-fuzzy
        db:
            index: umls_fuzzy
            settings:
                number_of_shards: 1
                number_of_replicas: 0
                max_result_window: 10000
            hosts: localhost:9200
            access_mode: c
            use_pipeline: true
            connect: true
            thread_count: 4
    install:
        filename: data/umls
        nrows: 38000


Search:
    class: umlsfacet
    conso_db:
        class: sqlite
        uri: db/umls
        table: conso
        access_mode: r
        connect: true
        serializer: pickle
        check_same_thread: false
    cuisty_db:
        class: sqlite
        uri: db/umls
        table: cuisty
        access_mode: r
        connect: true
        serializer: pickle
        check_same_thread: false
    matcher:
        class: elasticsearch-fuzzy
        db:
            index: umls_fuzzy
            settings:
                number_of_shards: 1
                number_of_replicas: 0
                max_result_window: 10000
            hosts: localhost:9200
            access_mode: r
            connect: true
        cache_db: dict
        rank: true
        exact_match: false
        fuzziness: AUTO
        prefix_length: 0
        max_expansions: 50
        transpositions: true
    tokenizer: alphanumeric
    formatter: json
