name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install pip
      run: |
        python -m pip install --upgrade pip
    - name: Install FACET and dependencies
      run: |
        pip install .
    - name: Lint with flake8
      run: |
        tox -e lint
    - name: Run tests
      run: |
        tox
    - name: Run FACET
      run: |
        python facet/scripts/cli.py run --config config/factory.yaml:FACET:Install --query "beautiful window in Apollo spacecraft"
